name: Manual Package

on:
  workflow_dispatch:

jobs:

  Build:

    name: Build
    runs-on: windows-latest

    steps:

      - name: Setup Python
        uses: actions/setup-python@v5.0.0
        with:
          python-version: '3.11.2'

      - name: Set Git to use LF
        run: |
          git config --global core.autocrlf false
          git config --global core.eol lf

      - name: Clone PyInstaller source
        uses: actions/checkout@v4.1.1
        with:
          repository: 'pyinstaller/pyinstaller'
          ref: 'v6.4.0'
          path: './pyinstaller'

      - name: Build PyInstaller bootloader
        run: |
          cd ./pyinstaller/bootloader
          python ./waf all --target-arch=64bit

      - name: Install PyInstaller
        run: |
          cd ./pyinstaller
          python -m pip install wheel
          pip install .

      - name: Clone repo
        uses: actions/checkout@v4.1.1
        with:
          path: './Spicetify-Easyinstall'

      - name: Build
        run: |
          cd .\Spicetify-Easyinstall
          python -m pip install -r requirements.txt
          pyinstaller --clean -y --dist dist\windows --workpath tmp build.spec
          
      - name: Cleanup
        shell: cmd
        run: |
          cd .\Spicetify-Easyinstall
          ls
          del  /f dist\windows\Spicetify-Easyinstall\_internal\opengl32sw.dll
          del  /f dist\windows\Spicetify-Easyinstall\_internal\Qt5DBus.dll
          del  /f dist\windows\Spicetify-Easyinstall\_internal\Qt5Network.dll
          del  /f dist\windows\Spicetify-Easyinstall\_internal\Qt5Qml.dll
          del  /f dist\windows\Spicetify-Easyinstall\_internal\Qt5QmlModels.dll
          del  /f dist\windows\Spicetify-Easyinstall\_internal\Qt5Quick.dll
          del  /f dist\windows\Spicetify-Easyinstall\_internal\Qt5Svg.dll
          del  /f dist\windows\Spicetify-Easyinstall\_internal\Qt5WebSockets.dll
          del  /f dist\windows\Spicetify-Easyinstall\_internal\libcrypto-1_1-x64.dll
          del  /f dist\windows\Spicetify-Easyinstall\_internal\libeay32.dll          
          del  /f dist\windows\Spicetify-Easyinstall\_internal\LIBPQ.dll          
          del  /f dist\windows\Spicetify-Easyinstall\_internal\libssl-1_1-x64.dll          
          del  /f dist\windows\Spicetify-Easyinstall\_internal\Qt5Bluetooth.dll          
          del  /f dist\windows\Spicetify-Easyinstall\_internal\Qt5Designer.dll          
          del  /f dist\windows\Spicetify-Easyinstall\_internal\Qt5Help.dll          
          del  /f dist\windows\Spicetify-Easyinstall\_internal\Qt5Location.dll          
          del  /f dist\windows\Spicetify-Easyinstall\_internal\Qt5Multimedia.dll          
          del  /f dist\windows\Spicetify-Easyinstall\_internal\Qt5MultimediaWidgets.dll          
          del  /f dist\windows\Spicetify-Easyinstall\_internal\Qt5NetworkAuth.dll          
          del  /f dist\windows\Spicetify-Easyinstall\_internal\Qt5Nfc.dll          
          del  /f dist\windows\Spicetify-Easyinstall\_internal\Qt5OpenGL.dll          
          del  /f dist\windows\Spicetify-Easyinstall\_internal\Qt5Positioning.dll          
          del  /f dist\windows\Spicetify-Easyinstall\_internal\Qt5PrintSupport.dll          
          del  /f dist\windows\Spicetify-Easyinstall\_internal\Qt5QmlWorkerScript.dll          
          del  /f dist\windows\Spicetify-Easyinstall\_internal\Qt5Quick3D.dll          
          del  /f dist\windows\Spicetify-Easyinstall\_internal\Qt5Quick3DAssetImport.dll          
          del  /f dist\windows\Spicetify-Easyinstall\_internal\Qt5Quick3DRender.dll          
          del  /f dist\windows\Spicetify-Easyinstall\_internal\Qt5Quick3DRuntimeRender.dll          
          del  /f dist\windows\Spicetify-Easyinstall\_internal\Qt5Quick3DUtils.dll          
          del  /f dist\windows\Spicetify-Easyinstall\_internal\Qt5QuickControls2.dll          
          del  /f dist\windows\Spicetify-Easyinstall\_internal\Qt5QuickParticles.dll          
          del  /f dist\windows\Spicetify-Easyinstall\_internal\Qt5QuickShapes.dll          
          del  /f dist\windows\Spicetify-Easyinstall\_internal\Qt5QuickTemplates2.dll          
          del  /f dist\windows\Spicetify-Easyinstall\_internal\Qt5QuickTest.dll          
          del  /f dist\windows\Spicetify-Easyinstall\_internal\Qt5QuickWidgets.dll          
          del  /f dist\windows\Spicetify-Easyinstall\_internal\Qt5RemoteObjects.dll          
          del  /f dist\windows\Spicetify-Easyinstall\_internal\Qt5Sensors.dll          
          del  /f dist\windows\Spicetify-Easyinstall\_internal\Qt5SerialPort.dll          
          del  /f dist\windows\Spicetify-Easyinstall\_internal\Qt5Sql.dll          
          del  /f dist\windows\Spicetify-Easyinstall\_internal\Qt5Test.dll          
          del  /f dist\windows\Spicetify-Easyinstall\_internal\Qt5TextToSpeech.dll          
          del  /f dist\windows\Spicetify-Easyinstall\_internal\Qt5WebChannel.dll          
          del  /f dist\windows\Spicetify-Easyinstall\_internal\Qt5WinExtras.dll          
          del  /f dist\windows\Spicetify-Easyinstall\_internal\Qt5Xml.dll          
          del  /f dist\windows\Spicetify-Easyinstall\_internal\Qt5XmlPatterns.dll          
          del  /f dist\windows\Spicetify-Easyinstall\_internal\ssleay32.dll          
          del  /f dist\windows\Spicetify-Easyinstall\_internal\Qt5PositioningQuick.dll      
          del  /f dist\windows\Spicetify-Easyinstall\_internal\PyQt5\Qt.pyd
          del  /f dist\windows\Spicetify-Easyinstall\_internal\PyQt5\QtBluetooth.pyd
          del  /f dist\windows\Spicetify-Easyinstall\_internal\PyQt5\QtDBus.pyd
          del  /f dist\windows\Spicetify-Easyinstall\_internal\PyQt5\QtDesigner.pyd
          del  /f dist\windows\Spicetify-Easyinstall\_internal\PyQt5\QtHelp.pyd
          del  /f dist\windows\Spicetify-Easyinstall\_internal\PyQt5\QtLocation.pyd
          del  /f dist\windows\Spicetify-Easyinstall\_internal\PyQt5\QtMultimedia.pyd
          del  /f dist\windows\Spicetify-Easyinstall\_internal\PyQt5\QtMultimediaWidgets.pyd
          del  /f dist\windows\Spicetify-Easyinstall\_internal\PyQt5\QtNetwork.pyd
          del  /f dist\windows\Spicetify-Easyinstall\_internal\PyQt5\QtNetworkAuth.pyd
          del  /f dist\windows\Spicetify-Easyinstall\_internal\PyQt5\QtNfc.pyd
          del  /f dist\windows\Spicetify-Easyinstall\_internal\PyQt5\QtOpenGL.pyd
          del  /f dist\windows\Spicetify-Easyinstall\_internal\PyQt5\QtPositioning.pyd
          del  /f dist\windows\Spicetify-Easyinstall\_internal\PyQt5\QtPrintSupport.pyd
          del  /f dist\windows\Spicetify-Easyinstall\_internal\PyQt5\QtQml.pyd
          del  /f dist\windows\Spicetify-Easyinstall\_internal\PyQt5\QtQuick.pyd
          del  /f dist\windows\Spicetify-Easyinstall\_internal\PyQt5\QtQuick3D.pyd
          del  /f dist\windows\Spicetify-Easyinstall\_internal\PyQt5\QtQuickWidgets.pyd
          del  /f dist\windows\Spicetify-Easyinstall\_internal\PyQt5\QtRemoteObjects.pyd
          del  /f dist\windows\Spicetify-Easyinstall\_internal\PyQt5\QtSensors.pyd
          del  /f dist\windows\Spicetify-Easyinstall\_internal\PyQt5\QtSerialPort.pyd
          del  /f dist\windows\Spicetify-Easyinstall\_internal\PyQt5\QtSql.pyd
          del  /f dist\windows\Spicetify-Easyinstall\_internal\PyQt5\QtSvg.pyd
          del  /f dist\windows\Spicetify-Easyinstall\_internal\PyQt5\QtTest.pyd
          del  /f dist\windows\Spicetify-Easyinstall\_internal\PyQt5\QtTextToSpeech.pyd
          del  /f dist\windows\Spicetify-Easyinstall\_internal\PyQt5\QtWebChannel.pyd
          del  /f dist\windows\Spicetify-Easyinstall\_internal\PyQt5\QtWebSockets.pyd
          del  /f dist\windows\Spicetify-Easyinstall\_internal\PyQt5\QtWinExtras.pyd
          del  /f dist\windows\Spicetify-Easyinstall\_internal\PyQt5\QtXml.pyd
          del  /f dist\windows\Spicetify-Easyinstall\_internal\PyQt5\QtXmlPatterns.pyd
          rmdir /S /Q dist\windows\Spicetify-Easyinstall\_internal\PyQt5\Qt\qml
          rmdir /S /Q dist\windows\Spicetify-Easyinstall\_internal\PyQt5\Qt\plugins\bearer
          rmdir /S /Q dist\windows\Spicetify-Easyinstall\_internal\PyQt5\Qt\plugins\mediaservice
          rmdir /S /Q dist\windows\Spicetify-Easyinstall\_internal\PyQt5\Qt\plugins\playlistformats
          rmdir /S /Q dist\windows\Spicetify-Easyinstall\_internal\PyQt5\Qt\plugins\printsupport
          rmdir /S /Q dist\windows\Spicetify-Easyinstall\_internal\PyQt5\Qt\plugins\sensorgestures
          rmdir /S /Q dist\windows\Spicetify-Easyinstall\_internal\PyQt5\Qt\plugins\sensors
          rmdir /S /Q dist\windows\Spicetify-Easyinstall\_internal\PyQt5\Qt\plugins\sqldrivers
          
      - name: Get short SHA string
        uses: benjlevesque/short-sha@v3.0
        id: short-sha
        with:
          length: 7

      - name: Zip package
        shell: cmd
        run: 7z a -r .\Spicetify-Easyinstall-manual-${{ steps.short-sha.outputs.sha }}.zip .\Spicetify-Easyinstall\dist\windows\Spicetify-Easyinstall\*

      - name: Upload Artifact
        uses: actions/upload-artifact@v4.3.1
        with:
          name: Spicetify-Easyinstall-manual-${{ steps.short-sha.outputs.sha }}
          path: ./Spicetify-Easyinstall-manual-${{ steps.short-sha.outputs.sha }}.zip
          retention-days: 1
