name: Package

on:
  push:
    branches: [ Spicetify-v2 ]

jobs:

  Build:

    name: Build
    runs-on: windows-latest
    if: "contains(github.event.head_commit.message, '+ PACKAGE')"

    steps:

      - name: Setup Python
        uses: actions/setup-python@v5.0.0
        with:
          python-version: '3.11.2'

      - name: Set Git to use LF
        run: |
          git config --global core.autocrlf false
          git config --global core.eol lf

      - name: Clone PyInstaller source
        uses: actions/checkout@v4.1.1
        with:
          repository: 'pyinstaller/pyinstaller'
          ref: 'v6.4.0'
          path: './pyinstaller'

      - name: Build PyInstaller bootloader
        run: |
          cd ./pyinstaller/bootloader
          python ./waf all --target-arch=64bit

      - name: Install PyInstaller
        run: |
          cd ./pyinstaller
          python -m pip install wheel
          pip install .

      - name: Clone repo
        uses: actions/checkout@v4.1.1
        with:
          path: './Spicetify-Easyinstall'

      - name: Build
        run: |
          cd .\Spicetify-Easyinstall
          python -m pip install -r requirements.txt
          pyinstaller --clean -y --dist dist\windows --workpath tmp build.spec
      
      - name: Get short SHA string
        uses: benjlevesque/short-sha@v3.0
        id: short-sha
        with:
          length: 7

      - name: Upload Artifact
        uses: actions/upload-artifact@v4.3.1
        with:
          name: Spicetify-Easyinstall-manual-${{ steps.short-sha.outputs.sha }}
          path: .\Spicetify-Easyinstall\dist\windows\Spicetify-Easyinstall\*
          retention-days: 1

